export const bankList = [
  { name: "Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)", shortName: "Vietcombank", bin: "970436" },
  { name: "Ngân hàng TMCP Kỹ Thương Việt Nam (Techcombank)", shortName: "Techcombank", bin: "970407" },
  { name: "Ngân hàng TMCP Quân Đội (MB Bank)", shortName: "MBBank", bin: "970422" },
  { name: "Ngân hàng TMCP Á Châu (ACB)", shortName: "ACB", bin: "970416" },
  { name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)", shortName: "BIDV", bin: "970418" },
  { name: "Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)", shortName: "VPBank", bin: "970432" },
  { name: "Ngân hàng TMCP Tiên Phong (TPBank)", shortName: "TPBank", bin: "970423" },
  { name: "Ngân hàng TMCP Hàng Hải Việt Nam (MSB)", shortName: "MSB", bin: "970426" },
  { name: "Ngân hàng TMCP Phương Đông (OCB)", shortName: "OCB", bin: "970448" },
  { name: "Ngân hàng TMCP Nam Á (Nam A Bank)", shortName: "Nam A Bank", bin: "970428" },
  { name: "Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)", shortName: "Sacombank", bin: "970403" },
  { name: "Ngân hàng TMCP HDBank", shortName: "HDBank", bin: "970437" },
  { name: "Ngân hàng TMCP An Bình (ABBank)", shortName: "ABBank", bin: "970425" },
  { name: "Ngân hàng TMCP Quốc tế Việt Nam (VIB)", shortName: "VIB", bin: "970441" },
  { name: "Ngân hàng TMCP Đông Á (DongA Bank)", shortName: "DongA Bank", bin: "970406" },
  { name: "Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)", shortName: "SHB", bin: "970443" },
  { name: "Ngân hàng TMCP Bắc Á (Bac A Bank)", shortName: "Bac A Bank", bin: "970409" },
  { name: "Ngân hàng TMCP Bản Việt (VietCapital Bank)", shortName: "VietCapital Bank", bin: "970454" },
  { name: "Ngân hàng TMCP Xăng Dầu Petrolimex (PG Bank)", shortName: "PG Bank", bin: "970430" },
  { name: "Ngân hàng TMCP Kiên Long (KienLongBank)", shortName: "KienLongBank", bin: "970452" },
  { name: "Ngân hàng TMCP Sài Gòn (SCB)", shortName: "SCB", bin: "970429" },
  { name: "Ngân hàng TMCP Đông Nam Á (SeABank)", shortName: "SeABank", bin: "970440" },
  { name: "Ngân hàng TMCP Bảo Việt (BaoViet Bank)", shortName: "BaoViet Bank", bin: "970438" },
  { name: "Ngân hàng TMCP Liên Việt (LPBank)", shortName: "LPBank", bin: "970449" },
  { name: "Ngân hàng TMCP Việt Á (VietABank)", shortName: "VietABank", bin: "970427" },
  { name: "Ngân hàng TMCP Đại Chúng (PVcomBank)", shortName: "PVcomBank", bin: "970412" },
  { name: "Ngân hàng TMCP Công Thương Việt Nam (VietinBank)", shortName: "VietinBank", bin: "970415" },
  { name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)", shortName: "Agribank", bin: "970405" },
  { name: "Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)", shortName: "SaigonBank", bin: "970400" },
  { name: "Ngân hàng TMCP Xây dựng (CBBank)", shortName: "CBBank", bin: "970444" },
  { name: "Ngân hàng TMCP Đại Tín (TrustBank cũ)", shortName: "TrustBank", bin: "970412" },
  { name: "Ngân hàng TMCP Dầu Khí Toàn Cầu (GPBank)", shortName: "GPBank", bin: "970408" },
  { name: "Ngân hàng TMCP Việt Nam Thương Tín (VietBank)", shortName: "VietBank", bin: "970433" },
  { name: "Ngân hàng TMCP Bưu Điện Liên Việt (LienVietPostBank)", shortName: "LienVietPostBank", bin: "970449" },
  { name: "Ngân hàng TNHH MTV Shinhan Việt Nam", shortName: "Shinhan", bin: "970424" },
  { name: "Ngân hàng TNHH MTV Woori Việt Nam", shortName: "Woori Bank", bin: "970457" },
  { name: "Ngân hàng TNHH MTV Hong Leong Việt Nam", shortName: "Hong Leong", bin: "970442" },
  { name: "Ngân hàng TNHH MTV Public Bank Việt Nam", shortName: "Public Bank", bin: "970439" },
  { name: "Ngân hàng TNHH MTV UOB Việt Nam", shortName: "UOB", bin: "970458" },
  { name: "Ngân hàng TNHH MTV CIMB Việt Nam", shortName: "CIMB", bin: "422589" },
  { name: "Ngân hàng TNHH MTV Standard Chartered Việt Nam", shortName: "Standard Chartered", bin: "970410" },
  { name: "Ngân hàng TNHH MTV HSBC Việt Nam", shortName: "HSBC", bin: "458761" },
  { name: "Ngân hàng TNHH MTV ANZ Việt Nam", shortName: "ANZ", bin: "970411" },
  { name: "Ngân hàng TNHH MTV Indovina", shortName: "Indovina", bin: "970434" },
  { name: "Ngân hàng TNHH MTV Hongkong and Shanghai (HSBC)", shortName: "HSBC", bin: "458761" },
  { name: "Ngân hàng TNHH MTV VID Public", shortName: "VID Public", bin: "970439" },
]
